# ============================================================
# Script 18k — Comparative Model Synthesis: Scripts 18g–18j
# Project: Add Health Adolescent Risk Models
#
# Purpose:
#   Consolidate and compare the main modelling results from:
#     18g: continuous total ISX model, 1–4 scale
#     18h: dependent-variable decomposition
#     18i: continuous method-use model among sexually active adolescents
#     18j: logistic high method protection among sexually active adolescents
#
# Main objective:
#   Produce aggregate synthesis tables for interpretation and reporting.
#
# Important:
#   This script does not create row-level data.
#   It reads only aggregate model outputs already generated by previous scripts.
#
# Git note:
#   Do not commit yet. This remains a model-review stage.
# ============================================================

rm(list = ls())

# ------------------------------------------------------------
# 0. Packages
# ------------------------------------------------------------

required_packages <- c(
  "dplyr",
  "tibble",
  "readr",
  "stringr",
  "tidyr",
  "purrr"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop("Missing packages: ", paste(missing_packages, collapse = ", "))
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(readr)
  library(stringr)
  library(tidyr)
  library(purrr)
})

has_officer <- requireNamespace("officer", quietly = TRUE)
has_flextable <- requireNamespace("flextable", quietly = TRUE)

if (has_officer) suppressPackageStartupMessages(library(officer))
if (has_flextable) suppressPackageStartupMessages(library(flextable))

# ------------------------------------------------------------
# 1. Project root and folders
# ------------------------------------------------------------

project_root <- "C:/Users/LENOVO/GitHub/add-health-adolescent-risk-models"

if (!dir.exists(project_root)) {
  stop("Project root not found: ", project_root)
}

setwd(project_root)

models_dir <- file.path(project_root, "outputs", "models")
docs_dir <- file.path(project_root, "docs")

dir.create(models_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(docs_dir, recursive = TRUE, showWarnings = FALSE)

cat("\n============================================================\n")
cat("Script 18k started: Comparative Model Synthesis\n")
cat("============================================================\n\n")

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

read_required_csv <- function(path) {
  if (!file.exists(path)) {
    stop("Required file not found: ", path)
  }

  readr::read_csv(path, show_col_types = FALSE)
}

safe_read_csv <- function(path) {
  if (!file.exists(path)) {
    return(NULL)
  }

  readr::read_csv(path, show_col_types = FALSE)
}

safe_num <- function(x) {
  suppressWarnings(as.numeric(x))
}

p_label <- function(p) {
  case_when(
    is.na(p) ~ NA_character_,
    p < 0.001 ~ "<0.001",
    TRUE ~ as.character(round(p, 3))
  )
}

sig_label <- function(p) {
  case_when(
    is.na(p) ~ "not available",
    p < 0.001 ~ "p < 0.001",
    p < 0.01 ~ "p < 0.01",
    p < 0.05 ~ "p < 0.05",
    p < 0.10 ~ "p < 0.10",
    TRUE ~ "not significant"
  )
}

direction_label <- function(x) {
  case_when(
    is.na(x) ~ "not available",
    x > 0 ~ "positive",
    x < 0 ~ "negative",
    TRUE ~ "zero"
  )
}

direction_label_by_type <- function(x, estimate_type) {
  case_when(
    is.na(x) ~ "not available",
    estimate_type == "odds ratio" & x > 1 ~ "positive",
    estimate_type == "odds ratio" & x < 1 ~ "negative",
    estimate_type == "odds ratio" & x == 1 ~ "zero",
    estimate_type == "beta" & x > 0 ~ "positive",
    estimate_type == "beta" & x < 0 ~ "negative",
    estimate_type == "beta" & x == 0 ~ "zero",
    TRUE ~ "not available"
  )
}



format_or <- function(or, low, high, p) {
  paste0(
    "OR = ", round(or, 3),
    ", 95% CI [", round(low, 3), ", ", round(high, 3), "]",
    ", p = ", p_label(p)
  )
}

format_beta <- function(beta, low, high, p) {
  paste0(
    "beta = ", round(beta, 4),
    ", 95% CI [", round(low, 4), ", ", round(high, 4), "]",
    ", p = ", p_label(p)
  )
}

extract_metric <- function(df, metric_name) {
  out <- df %>%
    filter(metric == metric_name) %>%
    pull(value)

  if (length(out) == 0) return(NA_character_)
  as.character(out[1])
}

# ------------------------------------------------------------
# 3. Input paths
# ------------------------------------------------------------

paths <- list(
  # 18g
  s18g_status = file.path(models_dir, "script18g_v2_final_status.csv"),
  s18g_sample = file.path(models_dir, "script18g_v2_continuous_model_sample_summary.csv"),
  s18g_fit = file.path(models_dir, "script18g_v2_continuous_model_fit.csv"),
  s18g_incremental = file.path(models_dir, "script18g_v2_continuous_model_incremental_r2.csv"),
  s18g_coef = file.path(models_dir, "script18g_v2_continuous_model_coefficients.csv"),
  s18g_vif = file.path(models_dir, "script18g_v2_continuous_final_model_vif.csv"),

  # 18h
  s18h_status = file.path(models_dir, "script18h_final_status.csv"),
  s18h_sample = file.path(models_dir, "script18h_model_sample_summary.csv"),
  s18h_outcome = file.path(models_dir, "script18h_outcome_summary.csv"),
  s18h_fit = file.path(models_dir, "script18h_model_fit.csv"),
  s18h_incremental = file.path(models_dir, "script18h_incremental_r2.csv"),
  s18h_key = file.path(models_dir, "script18h_key_coefficients_m4.csv"),
  s18h_knowledge = file.path(models_dir, "script18h_knowledge_coefficient_comparison.csv"),
  s18h_vif = file.path(models_dir, "script18h_vif.csv"),

  # 18i
  s18i_status = file.path(models_dir, "script18i_final_status.csv"),
  s18i_sample_flow = file.path(models_dir, "script18i_sample_flow.csv"),
  s18i_outcome = file.path(models_dir, "script18i_outcome_summary.csv"),
  s18i_fit = file.path(models_dir, "script18i_model_fit.csv"),
  s18i_incremental = file.path(models_dir, "script18i_incremental_r2.csv"),
  s18i_key = file.path(models_dir, "script18i_key_coefficients_m4.csv"),
  s18i_knowledge_selfeff = file.path(models_dir, "script18i_knowledge_selfeff_summary.csv"),
  s18i_vif = file.path(models_dir, "script18i_vif.csv"),

  # 18j
  s18j_status = file.path(models_dir, "script18j_final_status.csv"),
  s18j_sample_flow = file.path(models_dir, "script18j_sample_flow.csv"),
  s18j_outcome = file.path(models_dir, "script18j_outcome_summary.csv"),
  s18j_fit = file.path(models_dir, "script18j_model_fit.csv"),
  s18j_incremental = file.path(models_dir, "script18j_incremental_fit.csv"),
  s18j_key_or = file.path(models_dir, "script18j_key_coefficients_m4_or.csv"),
  s18j_knowledge_selfeff_or = file.path(models_dir, "script18j_knowledge_selfeff_summary_or.csv"),
  s18j_vif = file.path(models_dir, "script18j_vif.csv"),
  s18j_prediction = file.path(models_dir, "script18j_prediction_summary.csv")
)

missing_required <- unlist(paths)[!file.exists(unlist(paths))]

if (length(missing_required) > 0) {
  stop(
    "Some required aggregate output files are missing:\n",
    paste(missing_required, collapse = "\n")
  )
}

# ------------------------------------------------------------
# 4. Read aggregate outputs
# ------------------------------------------------------------

s18g_status <- read_required_csv(paths$s18g_status)
s18g_sample <- read_required_csv(paths$s18g_sample)
s18g_fit <- read_required_csv(paths$s18g_fit)
s18g_incremental <- read_required_csv(paths$s18g_incremental)
s18g_coef <- read_required_csv(paths$s18g_coef)
s18g_vif <- read_required_csv(paths$s18g_vif)

s18h_status <- read_required_csv(paths$s18h_status)
s18h_sample <- read_required_csv(paths$s18h_sample)
s18h_outcome <- read_required_csv(paths$s18h_outcome)
s18h_fit <- read_required_csv(paths$s18h_fit)
s18h_incremental <- read_required_csv(paths$s18h_incremental)
s18h_key <- read_required_csv(paths$s18h_key)
s18h_knowledge <- read_required_csv(paths$s18h_knowledge)
s18h_vif <- read_required_csv(paths$s18h_vif)

s18i_status <- read_required_csv(paths$s18i_status)
s18i_sample_flow <- read_required_csv(paths$s18i_sample_flow)
s18i_outcome <- read_required_csv(paths$s18i_outcome)
s18i_fit <- read_required_csv(paths$s18i_fit)
s18i_incremental <- read_required_csv(paths$s18i_incremental)
s18i_key <- read_required_csv(paths$s18i_key)
s18i_knowledge_selfeff <- read_required_csv(paths$s18i_knowledge_selfeff)
s18i_vif <- read_required_csv(paths$s18i_vif)

s18j_status <- read_required_csv(paths$s18j_status)
s18j_sample_flow <- read_required_csv(paths$s18j_sample_flow)
s18j_outcome <- read_required_csv(paths$s18j_outcome)
s18j_fit <- read_required_csv(paths$s18j_fit)
s18j_incremental <- read_required_csv(paths$s18j_incremental)
s18j_key_or <- read_required_csv(paths$s18j_key_or)
s18j_knowledge_selfeff_or <- read_required_csv(paths$s18j_knowledge_selfeff_or)
s18j_vif <- read_required_csv(paths$s18j_vif)
s18j_prediction <- read_required_csv(paths$s18j_prediction)

# ------------------------------------------------------------
# 5. Validation summary
# ------------------------------------------------------------

validation_summary <- bind_rows(
  tibble(
    script = "18g",
    model_family = "continuous OLS",
    all_checks_true = all(s18g_status$status == TRUE),
    failed_checks = paste(s18g_status$check[s18g_status$status != TRUE], collapse = "; ")
  ),
  tibble(
    script = "18h",
    model_family = "continuous OLS decomposition",
    all_checks_true = all(s18h_status$status == TRUE),
    failed_checks = paste(s18h_status$check[s18h_status$status != TRUE], collapse = "; ")
  ),
  tibble(
    script = "18i",
    model_family = "continuous OLS active method-use",
    all_checks_true = all(s18i_status$status == TRUE),
    failed_checks = paste(s18i_status$check[s18i_status$status != TRUE], collapse = "; ")
  ),
  tibble(
    script = "18j",
    model_family = "logistic high method protection",
    all_checks_true = all(s18j_status$status == TRUE),
    failed_checks = paste(s18j_status$check[s18j_status$status != TRUE], collapse = "; ")
  )
) %>%
  mutate(
    failed_checks = ifelse(failed_checks == "", NA_character_, failed_checks)
  )

# ------------------------------------------------------------
# 6. Model registry and sample comparison
# ------------------------------------------------------------

s18g_n <- safe_num(extract_metric(s18g_sample, "complete_case_model_n"))
s18g_dv_mean <- safe_num(extract_metric(s18g_sample, "dv_mean_1_4"))

s18h_n <- safe_num(extract_metric(s18h_sample, "common_complete_case_n"))

s18i_n <- s18i_sample_flow %>%
  filter(step == "complete_case_model_n") %>%
  pull(n)

s18j_n <- s18j_sample_flow %>%
  filter(step == "complete_case_model_n") %>%
  pull(n)

s18j_events <- safe_num(extract_metric(s18j_outcome, "events_high_method_protection"))
s18j_nonevents <- safe_num(extract_metric(s18j_outcome, "non_events_low_medium_protection"))
s18j_event_rate <- safe_num(extract_metric(s18j_outcome, "event_rate"))

model_registry <- tibble::tribble(
  ~script, ~model_label, ~estimator, ~dependent_variable, ~scale_or_link, ~analytic_sample, ~n,
  "18g", "Total ISX continuous model", "OLS", "Restricted ISX protection index", "1–4 continuous scale", "Aged 15–19 complete case", s18g_n,
  "18h", "Dependent-variable decomposition", "OLS", "Total index, timing component, method-use component", "1–4 continuous scale", "Aged 15–19 common complete case", s18h_n,
  "18i", "Active method-use continuous model", "OLS", "Method-use protection among sexually active adolescents", "1–3 continuous scale", "Aged 15–19 sexually active complete case", s18i_n,
  "18j", "High method protection logistic model", "Logistic regression", "High method protection", "1 = score 3; 0 = scores 1–2", "Aged 15–19 sexually active complete case", s18j_n
)

sample_comparison <- tibble::tribble(
  ~metric, ~script_18g, ~script_18h, ~script_18i, ~script_18j,
  "complete_case_n", s18g_n, s18h_n, s18i_n, s18j_n,
  "events_high_method_protection", NA_real_, NA_real_, NA_real_, s18j_events,
  "non_events_low_medium_protection", NA_real_, NA_real_, NA_real_, s18j_nonevents,
  "event_rate_high_method_protection", NA_real_, NA_real_, NA_real_, s18j_event_rate
)

# ------------------------------------------------------------
# 7. Final-model fit comparison
# ------------------------------------------------------------

fit_18g <- s18g_fit %>%
  filter(model == "M4_add_self_efficacy") %>%
  transmute(
    script = "18g",
    outcome = "total_restricted_isx_index",
    estimator = "OLS",
    n = n,
    final_fit_primary = r_squared,
    final_fit_primary_name = "R-squared",
    final_fit_secondary = adj_r_squared,
    final_fit_secondary_name = "Adjusted R-squared",
    aic = aic,
    bic = bic
  )

fit_18h <- s18h_fit %>%
  filter(model == "M4_add_self_efficacy") %>%
  transmute(
    script = "18h",
    outcome = outcome,
    estimator = "OLS",
    n = n,
    final_fit_primary = r_squared,
    final_fit_primary_name = "R-squared",
    final_fit_secondary = adj_r_squared,
    final_fit_secondary_name = "Adjusted R-squared",
    aic = aic,
    bic = bic
  )

fit_18i <- s18i_fit %>%
  filter(model == "M4_add_self_efficacy") %>%
  transmute(
    script = "18i",
    outcome = "method_use_active_continuous",
    estimator = "OLS",
    n = n,
    final_fit_primary = r_squared,
    final_fit_primary_name = "R-squared",
    final_fit_secondary = adj_r_squared,
    final_fit_secondary_name = "Adjusted R-squared",
    aic = aic,
    bic = bic
  )

fit_18j <- s18j_fit %>%
  filter(model == "M4_add_self_efficacy") %>%
  transmute(
    script = "18j",
    outcome = "high_method_protection",
    estimator = "Logit",
    n = n,
    final_fit_primary = mcfadden_r2,
    final_fit_primary_name = "McFadden R-squared",
    final_fit_secondary = brier_score,
    final_fit_secondary_name = "Brier score",
    aic = aic,
    bic = bic
  )

final_model_fit_comparison <- bind_rows(
  fit_18g,
  fit_18h,
  fit_18i,
  fit_18j
)

# ------------------------------------------------------------
# 8. Incremental contribution summary
# ------------------------------------------------------------

incremental_summary_18g <- s18g_incremental %>%
  filter(model %in% c("M2_covariates_perceptions", "M3_add_knowledge", "M4_add_self_efficacy")) %>%
  transmute(
    script = "18g",
    outcome = "total_restricted_isx_index",
    model_step = model,
    incremental_metric = "Delta R-squared",
    delta_value = delta_r_squared,
    interpretation = case_when(
      model == "M2_covariates_perceptions" ~ "Perceptions/barriers added",
      model == "M3_add_knowledge" ~ "Knowledge added",
      model == "M4_add_self_efficacy" ~ "Self-efficacy added",
      TRUE ~ model
    )
  )

incremental_summary_18h <- s18h_incremental %>%
  filter(model %in% c("M2_covariates_perceptions", "M3_add_knowledge", "M4_add_self_efficacy")) %>%
  transmute(
    script = "18h",
    outcome = outcome,
    model_step = model,
    incremental_metric = "Delta R-squared",
    delta_value = delta_r_squared,
    interpretation = case_when(
      model == "M2_covariates_perceptions" ~ "Perceptions/barriers added",
      model == "M3_add_knowledge" ~ "Knowledge added",
      model == "M4_add_self_efficacy" ~ "Self-efficacy added",
      TRUE ~ model
    )
  )

incremental_summary_18i <- s18i_incremental %>%
  filter(model %in% c("M2_covariates_perceptions", "M3_add_knowledge", "M4_add_self_efficacy")) %>%
  transmute(
    script = "18i",
    outcome = "method_use_active_continuous",
    model_step = model,
    incremental_metric = "Delta R-squared",
    delta_value = delta_r_squared,
    interpretation = case_when(
      model == "M2_covariates_perceptions" ~ "Perceptions/barriers added",
      model == "M3_add_knowledge" ~ "Knowledge added",
      model == "M4_add_self_efficacy" ~ "Self-efficacy added",
      TRUE ~ model
    )
  )

incremental_summary_18j <- s18j_incremental %>%
  filter(model %in% c("M2_covariates_perceptions", "M3_add_knowledge", "M4_add_self_efficacy")) %>%
  transmute(
    script = "18j",
    outcome = "high_method_protection",
    model_step = model,
    incremental_metric = "Delta McFadden R-squared",
    delta_value = delta_mcfadden_r2,
    interpretation = case_when(
      model == "M2_covariates_perceptions" ~ "Perceptions/barriers added",
      model == "M3_add_knowledge" ~ "Knowledge added",
      model == "M4_add_self_efficacy" ~ "Self-efficacy added",
      TRUE ~ model
    )
  )

incremental_contribution_summary <- bind_rows(
  incremental_summary_18g,
  incremental_summary_18h,
  incremental_summary_18i,
  incremental_summary_18j
)

# ------------------------------------------------------------
# 9. Knowledge and self-efficacy comparison
# ------------------------------------------------------------

knowledge_term <- "s19_knowledge_correct_count_0_10"
selfeff_term <- "s09_contraceptive_self_efficacy_index_1_5"

knowledge_18g <- s18g_coef %>%
  filter(model == "M4_add_self_efficacy", term == knowledge_term) %>%
  transmute(
    script = "18g",
    outcome = "total_restricted_isx_index",
    estimator = "OLS",
    construct = "Knowledge",
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value,
    formatted_result = format_beta(estimate, conf_low, conf_high, p_value)
  )

selfeff_18g <- s18g_coef %>%
  filter(model == "M4_add_self_efficacy", term == selfeff_term) %>%
  transmute(
    script = "18g",
    outcome = "total_restricted_isx_index",
    estimator = "OLS",
    construct = "Self-efficacy",
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value,
    formatted_result = format_beta(estimate, conf_low, conf_high, p_value)
  )

knowledge_18h <- s18h_knowledge %>%
  transmute(
    script = "18h",
    outcome = outcome,
    estimator = "OLS",
    construct = "Knowledge",
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value,
    formatted_result = format_beta(estimate, conf_low, conf_high, p_value)
  )

selfeff_18h <- s18h_key %>%
  filter(term == selfeff_term) %>%
  transmute(
    script = "18h",
    outcome = outcome,
    estimator = "OLS",
    construct = "Self-efficacy",
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value,
    formatted_result = format_beta(estimate, conf_low, conf_high, p_value)
  )

knowledge_selfeff_18i <- s18i_knowledge_selfeff %>%
  mutate(
    construct = case_when(
      term == knowledge_term ~ "Knowledge",
      term == selfeff_term ~ "Self-efficacy",
      TRUE ~ term
    )
  ) %>%
  transmute(
    script = "18i",
    outcome = "method_use_active_continuous",
    estimator = "OLS",
    construct = construct,
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value,
    formatted_result = format_beta(estimate, conf_low, conf_high, p_value)
  )

knowledge_selfeff_18j <- s18j_knowledge_selfeff_or %>%
  mutate(
    construct = case_when(
      term == knowledge_term ~ "Knowledge",
      term == selfeff_term ~ "Self-efficacy",
      TRUE ~ term
    )
  ) %>%
  transmute(
    script = "18j",
    outcome = "high_method_protection",
    estimator = "Logit",
    construct = construct,
    estimate_type = "odds ratio",
    estimate = odds_ratio,
    conf_low = or_conf_low,
    conf_high = or_conf_high,
    p_value = p_value,
    formatted_result = format_or(odds_ratio, or_conf_low, or_conf_high, p_value)
  )

knowledge_selfeff_comparison <- bind_rows(
  knowledge_18g,
  selfeff_18g,
  knowledge_18h,
  selfeff_18h,
  knowledge_selfeff_18i,
  knowledge_selfeff_18j
) %>%
  mutate(
    direction = direction_label_by_type(estimate, estimate_type),
    significance = sig_label(p_value)
  ) %>%
  arrange(construct, script, outcome)

# ------------------------------------------------------------
# 10. Pregnancy perception and susceptibility comparison
# ------------------------------------------------------------

pregnancy_terms <- c(
  "s08_pregnancy_consequence_severity_index_1_5",
  "s08_pregnancy_susceptibility_item_1_5",
  "s08_aids_susceptibility_item_1_5",
  "s08_std_protection_barrier_item_1_5"
)

perception_18g <- s18g_coef %>%
  filter(model == "M4_add_self_efficacy", term %in% pregnancy_terms) %>%
  transmute(
    script = "18g",
    outcome = "total_restricted_isx_index",
    estimator = "OLS",
    term = term,
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value
  )

perception_18h <- s18h_key %>%
  filter(term %in% pregnancy_terms) %>%
  transmute(
    script = "18h",
    outcome = outcome,
    estimator = "OLS",
    term = term,
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value
  )

perception_18i <- s18i_key %>%
  filter(term %in% pregnancy_terms) %>%
  transmute(
    script = "18i",
    outcome = "method_use_active_continuous",
    estimator = "OLS",
    term = term,
    estimate_type = "beta",
    estimate = estimate,
    conf_low = conf_low,
    conf_high = conf_high,
    p_value = p_value
  )

perception_18j <- s18j_key_or %>%
  filter(term %in% pregnancy_terms) %>%
  transmute(
    script = "18j",
    outcome = "high_method_protection",
    estimator = "Logit",
    term = term,
    estimate_type = "odds ratio",
    estimate = odds_ratio,
    conf_low = or_conf_low,
    conf_high = or_conf_high,
    p_value = p_value
  )

perception_comparison <- bind_rows(
  perception_18g,
  perception_18h,
  perception_18i,
  perception_18j
) %>%
  mutate(
    construct = case_when(
      term == "s08_pregnancy_consequence_severity_index_1_5" ~ "Pregnancy consequence severity",
      term == "s08_pregnancy_susceptibility_item_1_5" ~ "Pregnancy susceptibility",
      term == "s08_aids_susceptibility_item_1_5" ~ "AIDS susceptibility",
      term == "s08_std_protection_barrier_item_1_5" ~ "STD protection barrier",
      TRUE ~ term
    ),
    direction = direction_label_by_type(estimate, estimate_type),
    significance = sig_label(p_value)
  ) %>%
  arrange(construct, script, outcome)

# ------------------------------------------------------------
# 11. VIF summary
# ------------------------------------------------------------

vif_summary <- bind_rows(
  s18g_vif %>%
    mutate(script = "18g", outcome = "total_restricted_isx_index"),
  s18h_vif %>%
    mutate(script = "18h"),
  s18i_vif %>%
    mutate(script = "18i", outcome = "method_use_active_continuous"),
  s18j_vif %>%
    mutate(script = "18j", outcome = "high_method_protection")
) %>%
  group_by(script, outcome) %>%
  summarise(
    max_vif = max(vif, na.rm = TRUE),
    max_vif_term = term[which.max(vif)][1],
    .groups = "drop"
  ) %>%
  mutate(
    vif_interpretation = case_when(
      max_vif < 5 ~ "No serious multicollinearity concern",
      max_vif < 10 ~ "Moderate multicollinearity concern",
      TRUE ~ "High multicollinearity concern"
    )
  )

# ------------------------------------------------------------
# 12. Main findings synthesis
# ------------------------------------------------------------

main_findings <- tibble::tribble(
  ~finding_id, ~finding,
  "F1", "The total continuous ISX model showed a negative knowledge coefficient, but this result was not stable after restricting the sample to sexually active adolescents.",
  "F2", "Dependent-variable decomposition showed that the negative knowledge coefficient was strongest in the timing/abstinence component.",
  "F3", "Among sexually active adolescents, factual knowledge was not significantly associated with continuous method-use protection.",
  "F4", "In the logistic high-method-protection model, factual knowledge remained non-significant.",
  "F5", "Self-efficacy became positive and statistically significant once the analysis was restricted to sexually active adolescents.",
  "F6", "The logistic model confirmed self-efficacy as the strongest and most robust predictor of high method-use protection.",
  "F7", "Pregnancy consequence severity and pregnancy susceptibility were consistently positive predictors of protection, especially in method-use models.",
  "F8", "The models showed no serious multicollinearity problem; maximum VIF values remained below conventional concern thresholds.",
  "F9", "The preferred reporting strategy is to present the total ISX model as the broad adolescent protection model and the sexually active method-use models as mechanism-specific robustness analyses."
)

reporting_decisions <- tibble::tribble(
  ~decision_area, ~decision,
  "Primary descriptive model", "Report Script 18g as the broad continuous adolescent protection model using the restricted ISX index on the 1–4 scale.",
  "Diagnostic decomposition", "Use Script 18h to explain why the total index should not be interpreted as a pure method-use outcome.",
  "Mechanism-specific model", "Report Script 18i as the continuous method-use model among sexually active adolescents.",
  "Preferred method-use robustness model", "Report Script 18j as the binary robustness model for high method-use protection among sexually active adolescents.",
  "Knowledge interpretation", "Do not interpret knowledge as harmful. The negative coefficient in the total-index model is likely driven by the mixed abstinence/timing and method-use structure of the dependent variable.",
  "Self-efficacy interpretation", "Interpret self-efficacy as a robust predictor of method-use protection only among sexually active adolescents.",
  "Commit decision", "Do not commit yet. The current stage is model synthesis and interpretation review."
)

# ------------------------------------------------------------
# 13. Narrative paragraph for report
# ------------------------------------------------------------

narrative_for_report <- tibble(
  paragraph_id = c(
    "model_sequence",
    "knowledge_interpretation",
    "selfefficacy_interpretation",
    "reporting_strategy"
  ),
  text = c(
    paste0(
      "The modelling sequence proceeded from a broad continuous ISX protection model to ",
      "a dependent-variable decomposition and then to method-use models restricted to ",
      "sexually active adolescents. This structure was necessary because the total ISX ",
      "index combines sexual timing/abstinence and method-use protection."
    ),
    paste0(
      "The negative coefficient for factual knowledge in the total ISX model should not ",
      "be interpreted as evidence that knowledge reduces protection. After restricting ",
      "the analysis to sexually active adolescents and focusing on method-use protection, ",
      "knowledge was no longer statistically significant."
    ),
    paste0(
      "Contraceptive/protective self-efficacy emerged as the most robust predictor of ",
      "method-use protection among sexually active adolescents. This pattern was observed ",
      "both in the continuous method-use model and in the logistic model for high method-use protection."
    ),
    paste0(
      "The preferred reporting strategy is therefore to present the continuous total ISX ",
      "model as a broad adolescent protection model, while using the sexually active ",
      "method-use models to interpret behavioural protection among adolescents who have ",
      "already initiated sexual activity."
    )
  )
)

# ------------------------------------------------------------
# 14. Final status
# ------------------------------------------------------------

final_status <- tibble(
  check = c(
    "script18g_outputs_loaded",
    "script18h_outputs_loaded",
    "script18i_outputs_loaded",
    "script18j_outputs_loaded",
    "validation_summary_created",
    "model_registry_created",
    "sample_comparison_created",
    "final_model_fit_comparison_created",
    "incremental_contribution_summary_created",
    "knowledge_selfeff_comparison_created",
    "perception_comparison_created",
    "vif_summary_created",
    "main_findings_created",
    "reporting_decisions_created",
    "narrative_for_report_created",
    "no_row_level_output_created",
    "ready_for_interpretation_review"
  ),
  status = c(
    all(s18g_status$status == TRUE),
    all(s18h_status$status == TRUE),
    all(s18i_status$status == TRUE),
    all(s18j_status$status == TRUE),
    nrow(validation_summary) > 0,
    nrow(model_registry) > 0,
    nrow(sample_comparison) > 0,
    nrow(final_model_fit_comparison) > 0,
    nrow(incremental_contribution_summary) > 0,
    nrow(knowledge_selfeff_comparison) > 0,
    nrow(perception_comparison) > 0,
    nrow(vif_summary) > 0,
    nrow(main_findings) > 0,
    nrow(reporting_decisions) > 0,
    nrow(narrative_for_report) > 0,
    TRUE,
    TRUE
  )
)

# ------------------------------------------------------------
# 15. Optional Word report
# ------------------------------------------------------------

word_report_path <- file.path(
  docs_dir,
  "add_health_wave01_model_synthesis_script18k.docx"
)

if (has_officer && has_flextable) {

  make_ft <- function(x) {
    flextable::flextable(x) %>%
      flextable::fontsize(size = 8, part = "all") %>%
      flextable::padding(padding = 2, part = "all") %>%
      flextable::theme_booktabs() %>%
      flextable::autofit() %>%
      flextable::set_table_properties(width = 1, layout = "autofit")
  }

  doc <- officer::read_docx()

  doc <- doc %>%
    officer::body_add_par(
      "Add Health Wave I — Comparative Model Synthesis",
      style = "heading 1"
    ) %>%
    officer::body_add_par(
      "Script 18k consolidates the results from Scripts 18g, 18h, 18i and 18j.",
      style = "Normal"
    ) %>%
    officer::body_add_par("Validation summary", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(validation_summary)) %>%
    officer::body_add_par("Model registry", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(model_registry)) %>%
    officer::body_add_par("Sample comparison", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(sample_comparison)) %>%
    officer::body_add_par("Final model fit comparison", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(final_model_fit_comparison)) %>%
    officer::body_add_par("Incremental contribution summary", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(incremental_contribution_summary)) %>%
    officer::body_add_par("Knowledge and self-efficacy comparison", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(knowledge_selfeff_comparison)) %>%
    officer::body_add_par("Perception and susceptibility comparison", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(perception_comparison)) %>%
    officer::body_add_par("VIF summary", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(vif_summary)) %>%
    officer::body_add_par("Main findings", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(main_findings)) %>%
    officer::body_add_par("Reporting decisions", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(reporting_decisions)) %>%
    officer::body_add_par("Narrative for report", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(narrative_for_report)) %>%
    officer::body_add_par("Final status", style = "heading 2") %>%
    flextable::body_add_flextable(make_ft(final_status))

  print(doc, target = word_report_path)

} else {
  word_report_path <- NA_character_
}

final_status <- final_status %>%
  bind_rows(
    tibble(
      check = "word_report_created",
      status = !is.na(word_report_path) && file.exists(word_report_path)
    )
  )

# ------------------------------------------------------------
# 16. Write aggregate outputs
# ------------------------------------------------------------

write_csv(
  final_status,
  file.path(models_dir, "script18k_final_status.csv")
)

write_csv(
  validation_summary,
  file.path(models_dir, "script18k_validation_summary.csv")
)

write_csv(
  model_registry,
  file.path(models_dir, "script18k_model_registry.csv")
)

write_csv(
  sample_comparison,
  file.path(models_dir, "script18k_sample_comparison.csv")
)

write_csv(
  final_model_fit_comparison,
  file.path(models_dir, "script18k_final_model_fit_comparison.csv")
)

write_csv(
  incremental_contribution_summary,
  file.path(models_dir, "script18k_incremental_contribution_summary.csv")
)

write_csv(
  knowledge_selfeff_comparison,
  file.path(models_dir, "script18k_knowledge_selfeff_comparison.csv")
)

write_csv(
  perception_comparison,
  file.path(models_dir, "script18k_perception_comparison.csv")
)

write_csv(
  vif_summary,
  file.path(models_dir, "script18k_vif_summary.csv")
)

write_csv(
  main_findings,
  file.path(models_dir, "script18k_main_findings.csv")
)

write_csv(
  reporting_decisions,
  file.path(models_dir, "script18k_reporting_decisions.csv")
)

write_csv(
  narrative_for_report,
  file.path(models_dir, "script18k_narrative_for_report.csv")
)

# ------------------------------------------------------------
# 17. Console output
# ------------------------------------------------------------

cat("\n============================================================\n")
cat("Script 18k completed: Comparative Model Synthesis\n")
cat("============================================================\n\n")

cat("Final status:\n")
print(final_status, n = Inf)

cat("\nValidation summary:\n")
print(validation_summary, n = Inf)

cat("\nModel registry:\n")
print(model_registry, n = Inf)

cat("\nSample comparison:\n")
print(sample_comparison, n = Inf)

cat("\nFinal model fit comparison:\n")
print(final_model_fit_comparison, n = Inf)

cat("\nIncremental contribution summary:\n")
print(incremental_contribution_summary, n = Inf)

cat("\nKnowledge and self-efficacy comparison:\n")
print(knowledge_selfeff_comparison, n = Inf)

cat("\nPerception and susceptibility comparison:\n")
print(perception_comparison, n = Inf)

cat("\nVIF summary:\n")
print(vif_summary, n = Inf)

cat("\nMain findings:\n")
print(main_findings, n = Inf)

cat("\nReporting decisions:\n")
print(reporting_decisions, n = Inf)

cat("\nNarrative for report:\n")
print(narrative_for_report, n = Inf)

cat("\nOutputs created in:\n")
cat(models_dir, "\n")

if (!is.na(word_report_path)) {
  cat("\nWord report:\n")
  cat(word_report_path, "\n")
}

cat("\nImportant Git note:\n")
cat("Script 18k creates aggregate synthesis outputs only.\n")
cat("No row-level LOCAL_ONLY file is created by this script.\n")
cat("Do not commit yet. Review interpretation first.\n")