# ============================================================
# Script 18l — Final Modelling Interpretation Report
# Project: Add Health Adolescent Risk Models
#
# Purpose:
#   Produce a final interpretive Word report from the validated
#   aggregate outputs generated by Scripts 18g, 18h, 18i, 18j and 18k.
#
# This script:
#   - reads aggregate outputs only;
#   - creates no row-level dataset;
#   - generates a final interpretation report in DOCX format;
#   - exports supporting aggregate interpretation tables.
#
# Main interpretive conclusion:
#   Knowledge appears negative in the broad total ISX model because
#   the total index combines timing/abstinence and method-use.
#   Among sexually active adolescents, knowledge is not significant,
#   while self-efficacy becomes the robust predictor of method-use
#   protection.
#
# Git note:
#   Do not commit yet. Review the final report first.
# ============================================================

rm(list = ls())

# ------------------------------------------------------------
# 0. Packages
# ------------------------------------------------------------

required_packages <- c(
  "dplyr",
  "tibble",
  "readr",
  "stringr",
  "tidyr",
  "purrr",
  "officer",
  "flextable"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop("Missing packages: ", paste(missing_packages, collapse = ", "))
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(readr)
  library(stringr)
  library(tidyr)
  library(purrr)
  library(officer)
  library(flextable)
})

# ------------------------------------------------------------
# 1. Project root and folders
# ------------------------------------------------------------

project_root <- "C:/Users/LENOVO/GitHub/add-health-adolescent-risk-models"

if (!dir.exists(project_root)) {
  stop("Project root not found: ", project_root)
}

setwd(project_root)

models_dir <- file.path(project_root, "outputs", "models")
docs_dir   <- file.path(project_root, "docs")

dir.create(models_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(docs_dir, recursive = TRUE, showWarnings = FALSE)

cat("\n============================================================\n")
cat("Script 18l started: Final Modelling Interpretation Report\n")
cat("============================================================\n\n")

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

read_required_csv <- function(path) {
  if (!file.exists(path)) {
    stop("Required file not found: ", path)
  }

  readr::read_csv(path, show_col_types = FALSE)
}

format_p <- function(p) {
  p <- suppressWarnings(as.numeric(p))

  case_when(
    is.na(p) ~ "NA",
    p < 0.001 ~ "<0.001",
    TRUE ~ as.character(round(p, 3))
  )
}

format_num <- function(x, digits = 3) {
  x <- suppressWarnings(as.numeric(x))

  ifelse(
    is.na(x),
    "NA",
    format(round(x, digits), nsmall = digits, trim = TRUE)
  )
}

clean_for_word <- function(df, digits = 4) {
  df %>%
    mutate(
      across(
        where(is.numeric),
        ~ round(.x, digits)
      )
    ) %>%
    mutate(
      across(
        everything(),
        ~ as.character(.x)
      )
    ) %>%
    mutate(
      across(
        everything(),
        ~ ifelse(is.na(.x), "", .x)
      )
    )
}

make_ft <- function(df, digits = 4) {
  df_clean <- clean_for_word(df, digits = digits)

  flextable(df_clean) %>%
    fontsize(size = 8, part = "all") %>%
    padding(padding = 2, part = "all") %>%
    theme_booktabs() %>%
    autofit() %>%
    set_table_properties(width = 1, layout = "autofit")
}

add_heading <- function(doc, text, level = 1) {
  style_name <- paste0("heading ", level)
  officer::body_add_par(doc, text, style = style_name)
}

add_paragraphs <- function(doc, paragraphs) {
  for (p in paragraphs) {
    doc <- officer::body_add_par(doc, p, style = "Normal")
  }

  doc
}

add_table_section <- function(doc, title, df, level = 2) {
  doc <- add_heading(doc, title, level = level)
  doc <- flextable::body_add_flextable(doc, make_ft(df))
  doc <- officer::body_add_par(doc, "", style = "Normal")

  doc
}

get_result <- function(df, script_id, construct_name, outcome_pattern = NULL) {

  out <- df %>%
    filter(
      script == script_id,
      construct == construct_name
    )

  if (!is.null(outcome_pattern)) {
    out <- out %>%
      filter(stringr::str_detect(outcome, outcome_pattern))
  }

  if (nrow(out) == 0) {
    return(NA_character_)
  }

  out$formatted_result[1]
}

get_perception_result <- function(df, script_id, construct_name, outcome_pattern = NULL) {

  out <- df %>%
    filter(
      script == script_id,
      construct == construct_name
    )

  if (!is.null(outcome_pattern)) {
    out <- out %>%
      filter(stringr::str_detect(outcome, outcome_pattern))
  }

  if (nrow(out) == 0) {
    return(NA_character_)
  }

  if (out$estimate_type[1] == "odds ratio") {
    paste0(
      "OR = ", format_num(out$estimate[1], 3),
      ", 95% CI [", format_num(out$conf_low[1], 3),
      ", ", format_num(out$conf_high[1], 3),
      "], p = ", format_p(out$p_value[1])
    )
  } else {
    paste0(
      "beta = ", format_num(out$estimate[1], 4),
      ", 95% CI [", format_num(out$conf_low[1], 4),
      ", ", format_num(out$conf_high[1], 4),
      "], p = ", format_p(out$p_value[1])
    )
  }
}

# ------------------------------------------------------------
# 3. Required aggregate input files
# ------------------------------------------------------------

paths <- list(
  s18k_status = file.path(models_dir, "script18k_final_status.csv"),
  validation_summary = file.path(models_dir, "script18k_validation_summary.csv"),
  model_registry = file.path(models_dir, "script18k_model_registry.csv"),
  sample_comparison = file.path(models_dir, "script18k_sample_comparison.csv"),
  final_model_fit_comparison = file.path(models_dir, "script18k_final_model_fit_comparison.csv"),
  incremental_contribution_summary = file.path(models_dir, "script18k_incremental_contribution_summary.csv"),
  knowledge_selfeff_comparison = file.path(models_dir, "script18k_knowledge_selfeff_comparison.csv"),
  perception_comparison = file.path(models_dir, "script18k_perception_comparison.csv"),
  vif_summary = file.path(models_dir, "script18k_vif_summary.csv"),
  main_findings = file.path(models_dir, "script18k_main_findings.csv"),
  reporting_decisions = file.path(models_dir, "script18k_reporting_decisions.csv"),
  narrative_for_report = file.path(models_dir, "script18k_narrative_for_report.csv"),

  s18g_fit = file.path(models_dir, "script18g_v2_continuous_model_fit.csv"),
  s18h_fit = file.path(models_dir, "script18h_model_fit.csv"),
  s18i_fit = file.path(models_dir, "script18i_model_fit.csv"),
  s18j_fit = file.path(models_dir, "script18j_model_fit.csv"),
  s18j_outcome = file.path(models_dir, "script18j_outcome_summary.csv")
)

missing_required <- unlist(paths)[!file.exists(unlist(paths))]

if (length(missing_required) > 0) {
  stop(
    "Some required aggregate output files are missing:\n",
    paste(missing_required, collapse = "\n")
  )
}

# ------------------------------------------------------------
# 4. Read aggregate outputs
# ------------------------------------------------------------

s18k_status <- read_required_csv(paths$s18k_status)
validation_summary <- read_required_csv(paths$validation_summary)
model_registry <- read_required_csv(paths$model_registry)
sample_comparison <- read_required_csv(paths$sample_comparison)
final_model_fit_comparison <- read_required_csv(paths$final_model_fit_comparison)
incremental_contribution_summary <- read_required_csv(paths$incremental_contribution_summary)
knowledge_selfeff_comparison <- read_required_csv(paths$knowledge_selfeff_comparison)
perception_comparison <- read_required_csv(paths$perception_comparison)
vif_summary <- read_required_csv(paths$vif_summary)
main_findings <- read_required_csv(paths$main_findings)
reporting_decisions <- read_required_csv(paths$reporting_decisions)
narrative_for_report <- read_required_csv(paths$narrative_for_report)

s18g_fit <- read_required_csv(paths$s18g_fit)
s18h_fit <- read_required_csv(paths$s18h_fit)
s18i_fit <- read_required_csv(paths$s18i_fit)
s18j_fit <- read_required_csv(paths$s18j_fit)
s18j_outcome <- read_required_csv(paths$s18j_outcome)

# ------------------------------------------------------------
# 5. Extract key results for narrative
# ------------------------------------------------------------

knowledge_total <- get_result(
  knowledge_selfeff_comparison,
  "18g",
  "Knowledge",
  "total_restricted"
)

knowledge_active_continuous <- get_result(
  knowledge_selfeff_comparison,
  "18i",
  "Knowledge",
  "method_use_active"
)

knowledge_active_logit <- get_result(
  knowledge_selfeff_comparison,
  "18j",
  "Knowledge",
  "high_method"
)

selfeff_total <- get_result(
  knowledge_selfeff_comparison,
  "18g",
  "Self-efficacy",
  "total_restricted"
)

selfeff_active_continuous <- get_result(
  knowledge_selfeff_comparison,
  "18i",
  "Self-efficacy",
  "method_use_active"
)

selfeff_active_logit <- get_result(
  knowledge_selfeff_comparison,
  "18j",
  "Self-efficacy",
  "high_method"
)

preg_consequence_logit <- get_perception_result(
  perception_comparison,
  "18j",
  "Pregnancy consequence severity",
  "high_method"
)

preg_suscept_logit <- get_perception_result(
  perception_comparison,
  "18j",
  "Pregnancy susceptibility",
  "high_method"
)

aids_suscept_logit <- get_perception_result(
  perception_comparison,
  "18j",
  "AIDS susceptibility",
  "high_method"
)

barrier_logit <- get_perception_result(
  perception_comparison,
  "18j",
  "STD protection barrier",
  "high_method"
)

n_18g <- model_registry %>%
  filter(script == "18g") %>%
  pull(n) %>%
  as.numeric()

n_18i <- model_registry %>%
  filter(script == "18i") %>%
  pull(n) %>%
  as.numeric()

n_18j <- model_registry %>%
  filter(script == "18j") %>%
  pull(n) %>%
  as.numeric()

event_rate_18j <- sample_comparison %>%
  filter(metric == "event_rate_high_method_protection") %>%
  pull(script_18j) %>%
  as.numeric()

# ------------------------------------------------------------
# 6. Create interpretation tables
# ------------------------------------------------------------

core_interpretation_summary <- tibble::tribble(
  ~topic, ~interpretation,
  "Broad ISX model",
  "The broad continuous ISX model is useful as a general adolescent protection model, but it should not be interpreted as a pure method-use model because it combines timing/abstinence and method-use protection.",

  "Knowledge",
  "Factual knowledge is negative in the total ISX model and in the decomposition models, but it becomes non-significant after restricting the sample to sexually active adolescents. Therefore, knowledge should not be interpreted as harmful.",

  "Self-efficacy",
  "Self-efficacy is not relevant in the total ISX model, but becomes positive and statistically significant in the method-use models restricted to sexually active adolescents.",

  "Pregnancy perceptions",
  "Pregnancy consequence severity and pregnancy susceptibility are consistently positive predictors of protection and remain relevant in the high method-protection logistic model.",

  "AIDS susceptibility",
  "AIDS susceptibility is positive in broad/decomposition models and marginal in the logistic high method-protection model, but it is not the strongest mechanism among sexually active adolescents.",

  "STD protection barrier",
  "The STD protection barrier is generally negative but not statistically significant. It should not be emphasized as a central finding.",

  "Multicollinearity",
  "VIF diagnostics do not indicate serious multicollinearity problems. The highest VIF values are associated with grade and age, which is expected."
)

preferred_reporting_models <- tibble::tribble(
  ~report_section, ~model_to_report, ~reason,
  "Main model",
  "Script 18g - Total ISX continuous model",
  "Provides the broad adolescent sexual protection model on the original 1-4 ISX scale.",

  "Diagnostic model",
  "Script 18h - Dependent-variable decomposition",
  "Shows that the total index combines timing/abstinence and method-use, explaining why knowledge behaves differently in the broad model.",

  "Mechanism model",
  "Script 18i - Active method-use continuous model",
  "Restricts the analysis to sexually active adolescents and focuses directly on method-use protection.",

  "Robustness model",
  "Script 18j - Logistic high method protection",
  "Confirms the method-use result with a binary high-protection outcome and interpretable odds ratios."
)

key_results_narrative_table <- tibble::tribble(
  ~construct, ~broad_total_isx_result, ~sexually_active_method_use_result, ~interpretation,
  "Knowledge",
  knowledge_total,
  paste0("Continuous: ", knowledge_active_continuous, "; Logistic: ", knowledge_active_logit),
  "Not a robust direct predictor of method-use protection after restricting to sexually active adolescents.",

  "Self-efficacy",
  selfeff_total,
  paste0("Continuous: ", selfeff_active_continuous, "; Logistic: ", selfeff_active_logit),
  "Robust positive predictor of method-use protection among sexually active adolescents.",

  "Pregnancy consequence severity",
  "Positive and significant in the broad and decomposition models.",
  preg_consequence_logit,
  "Consistent protective perception mechanism.",

  "Pregnancy susceptibility",
  "Positive and significant in the broad and decomposition models.",
  preg_suscept_logit,
  "Consistent protective perception mechanism.",

  "AIDS susceptibility",
  "Positive in broad/decomposition models.",
  aids_suscept_logit,
  "Weaker and less robust than pregnancy-related perceptions in active method-use models.",

  "STD protection barrier",
  "Negative but not significant in the broad/decomposition models.",
  barrier_logit,
  "Not a central result."
)

limitations_table <- tibble::tribble(
  ~limitation, ~interpretation_for_report,
  "Cross-sectional design",
  "The models identify associations and should not be interpreted as causal effects.",

  "Restricted public-use outcome",
  "The ISX index is restricted to variables available in the public-use data and does not include all behavioral dimensions originally considered in the thesis architecture.",

  "Mixed structure of total ISX",
  "The total ISX index combines timing/abstinence and method-use. This is analytically useful but requires careful interpretation.",

  "Outcome imbalance in logistic model",
  "High method protection is common among sexually active respondents, so the binary model has an imbalanced outcome.",

  "Low explained variance",
  "The R-squared and pseudo-R-squared values are modest, which is common in individual-level behavioral models and indicates that unobserved factors remain important.",

  "Knowledge measurement",
  "The knowledge score is a factual quiz and should not be treated as a complete measure of health literacy, sexual education quality or behavioral competence."
)

# ------------------------------------------------------------
# 7. Create narrative text
# ------------------------------------------------------------

executive_summary <- c(
  paste0(
    "This report synthesizes the final modelling sequence for the Add Health Wave I adolescent sexual protection analysis. ",
    "The modelling strategy moved from a broad restricted ISX protection index to decomposed and sexually active-only method-use models. ",
    "This sequence was required because the total ISX index combines timing/abstinence and method-use protection."
  ),
  paste0(
    "The broad continuous ISX model included ", n_18g,
    " respondents aged 15-19. The sexually active method-use models included ",
    n_18i, " respondents. In the logistic high method-protection model, the event rate was ",
    round(100 * event_rate_18j, 1), "%."
  ),
  paste0(
    "The key substantive result is that factual knowledge should not be interpreted as reducing protection. ",
    "It appears negative in the total ISX model, but becomes non-significant when the analysis is restricted to sexually active adolescents. ",
    "By contrast, contraceptive/protective self-efficacy becomes a robust positive predictor of method-use protection among sexually active adolescents."
  )
)

model_sequence_text <- c(
  "The modelling sequence was designed to separate broad adolescent protection from method-use behavior among sexually active adolescents.",
  "Script 18g estimated the main continuous model using the restricted ISX protection index on the original 1-4 scale.",
  "Script 18h decomposed the dependent variable into the total ISX index, timing/abstinence component and method-use component.",
  "Script 18i restricted the sample to sexually active adolescents and modelled continuous method-use protection.",
  "Script 18j estimated a logistic model for high method-use protection among sexually active adolescents.",
  "Script 18k consolidated these outputs and verified that all models were successfully estimated and that no row-level synthesis output was created."
)

knowledge_text <- c(
  paste0(
    "In the total ISX model, factual knowledge showed a negative coefficient: ",
    knowledge_total, ". "
  ),
  paste0(
    "However, after restricting the sample to sexually active adolescents, knowledge was no longer significant in the continuous method-use model: ",
    knowledge_active_continuous, ". "
  ),
  paste0(
    "The same conclusion was obtained in the logistic high method-protection model: ",
    knowledge_active_logit, ". "
  ),
  "This pattern indicates that the negative knowledge coefficient in the total ISX model is likely driven by the mixed structure of the dependent variable rather than by a harmful effect of knowledge."
)

selfeff_text <- c(
  paste0(
    "Self-efficacy was not a meaningful predictor in the broad total ISX model: ",
    selfeff_total, ". "
  ),
  paste0(
    "When the sample was restricted to sexually active adolescents, self-efficacy became positive and statistically significant in the continuous method-use model: ",
    selfeff_active_continuous, ". "
  ),
  paste0(
    "The logistic model confirmed this pattern: ",
    selfeff_active_logit, ". "
  ),
  "The interpretation is that perceived ability to plan, use or negotiate birth control is most relevant once adolescents are sexually active and method-use becomes the behavioral outcome of interest."
)

perception_text <- c(
  paste0(
    "Pregnancy consequence severity was consistently positive. In the logistic high method-protection model, the result was: ",
    preg_consequence_logit, ". "
  ),
  paste0(
    "Pregnancy susceptibility was also positive and significant in the logistic model: ",
    preg_suscept_logit, ". "
  ),
  paste0(
    "AIDS susceptibility was weaker in the logistic model: ",
    aids_suscept_logit, ". "
  ),
  paste0(
    "The STD protection barrier was not statistically significant: ",
    barrier_logit, ". "
  ),
  "The final interpretation should emphasize pregnancy-related perceptions and self-efficacy as the strongest and most consistent mechanisms."
)

reporting_strategy_text <- c(
  "The recommended reporting strategy is not to select a single model and discard the others. Instead, the models should be presented as a structured sequence.",
  "The total ISX model should be used as the main broad adolescent protection model.",
  "The decomposition should be used to explain why the broad ISX outcome requires careful interpretation.",
  "The sexually active method-use models should be used to interpret behavioral method-use protection among adolescents who have initiated sexual activity.",
  "The logistic model should be used as the most interpretable robustness model because it expresses the result in odds ratios for high method-use protection."
)

conclusion_text <- c(
  "The final modelling evidence supports a differentiated interpretation of adolescent sexual protection.",
  "For the full adolescent sample, perceived pregnancy consequences and susceptibility are consistently associated with higher protection scores.",
  "For sexually active adolescents, self-efficacy becomes the most robust predictor of method-use protection.",
  "Factual knowledge is not a robust direct predictor of method-use once the analysis is restricted to sexually active adolescents.",
  "The final report should therefore avoid the statement that knowledge reduces protection and should instead state that the negative knowledge coefficient in the broad ISX model reflects the mixed timing/abstinence and method-use structure of the outcome."
)

final_report_sections <- tibble(
  section = c(
    "Executive summary",
    "Model sequence",
    "Knowledge interpretation",
    "Self-efficacy interpretation",
    "Risk perception interpretation",
    "Reporting strategy",
    "Conclusion"
  ),
  text = c(
    paste(executive_summary, collapse = "\n"),
    paste(model_sequence_text, collapse = "\n"),
    paste(knowledge_text, collapse = "\n"),
    paste(selfeff_text, collapse = "\n"),
    paste(perception_text, collapse = "\n"),
    paste(reporting_strategy_text, collapse = "\n"),
    paste(conclusion_text, collapse = "\n")
  )
)

# ------------------------------------------------------------
# 8. Build Word report
# ------------------------------------------------------------

word_report_path <- file.path(
  docs_dir,
  "add_health_wave01_final_modelling_interpretation_report_script18l.docx"
)

doc <- officer::read_docx()

doc <- doc %>%
  officer::body_add_par(
    "Add Health Wave I - Final Modelling Interpretation Report",
    style = "heading 1"
  ) %>%
  officer::body_add_par(
    "Scripts 18g-18l: Restricted ISX protection, decomposition, active method-use and high method-protection models",
    style = "Normal"
  ) %>%
  officer::body_add_par(
    paste0("Generated from aggregate outputs only. Project root: ", project_root),
    style = "Normal"
  ) %>%
  officer::body_add_par(
    "Data protection note: this report uses aggregate outputs only and creates no row-level dataset.",
    style = "Normal"
  ) %>%
  officer::body_add_break()

doc <- add_heading(doc, "1. Executive summary", level = 1)
doc <- add_paragraphs(doc, executive_summary)

doc <- add_heading(doc, "2. Modelling sequence", level = 1)
doc <- add_paragraphs(doc, model_sequence_text)
doc <- add_table_section(doc, "Model registry", model_registry, level = 2)
doc <- add_table_section(doc, "Sample comparison", sample_comparison, level = 2)
doc <- add_table_section(doc, "Validation summary", validation_summary, level = 2)

doc <- add_heading(doc, "3. Final model fit", level = 1)
doc <- add_paragraphs(
  doc,
  c(
    "Model fit was modest across specifications, which is expected for individual-level behavioral outcomes.",
    "The final fit table should be interpreted comparatively, not as evidence of high predictive performance.",
    "The key issue is the direction, stability and interpretation of the construct-level coefficients across the modelling sequence."
  )
)
doc <- add_table_section(
  doc,
  "Final model fit comparison",
  final_model_fit_comparison,
  level = 2
)

doc <- add_table_section(
  doc,
  "Incremental contribution summary",
  incremental_contribution_summary,
  level = 2
)

doc <- add_heading(doc, "4. Knowledge interpretation", level = 1)
doc <- add_paragraphs(doc, knowledge_text)

doc <- add_heading(doc, "5. Self-efficacy interpretation", level = 1)
doc <- add_paragraphs(doc, selfeff_text)

doc <- add_heading(doc, "6. Perceived risk and susceptibility interpretation", level = 1)
doc <- add_paragraphs(doc, perception_text)

doc <- add_table_section(
  doc,
  "Knowledge and self-efficacy comparison",
  knowledge_selfeff_comparison,
  level = 2
)

doc <- add_table_section(
  doc,
  "Perception and susceptibility comparison",
  perception_comparison,
  level = 2
)

doc <- add_heading(doc, "7. Core interpretation summary", level = 1)
doc <- add_table_section(
  doc,
  "Core interpretation summary",
  core_interpretation_summary,
  level = 2
)

doc <- add_table_section(
  doc,
  "Key results narrative table",
  key_results_narrative_table,
  level = 2
)

doc <- add_heading(doc, "8. Preferred reporting strategy", level = 1)
doc <- add_paragraphs(doc, reporting_strategy_text)

doc <- add_table_section(
  doc,
  "Preferred reporting models",
  preferred_reporting_models,
  level = 2
)

doc <- add_table_section(
  doc,
  "Reporting decisions from Script 18k",
  reporting_decisions,
  level = 2
)

doc <- add_heading(doc, "9. Diagnostics and limitations", level = 1)
doc <- add_paragraphs(
  doc,
  c(
    "The VIF diagnostics do not indicate serious multicollinearity problems.",
    "Age and grade show the largest VIF values, which is expected because school grade is strongly age-related.",
    "The limitations below should be explicitly acknowledged in the report or article."
  )
)

doc <- add_table_section(
  doc,
  "VIF summary",
  vif_summary,
  level = 2
)

doc <- add_table_section(
  doc,
  "Limitations and interpretation cautions",
  limitations_table,
  level = 2
)

doc <- add_heading(doc, "10. Final conclusion", level = 1)
doc <- add_paragraphs(doc, conclusion_text)

doc <- add_heading(doc, "11. Main findings from Script 18k", level = 1)
doc <- add_table_section(
  doc,
  "Main findings",
  main_findings,
  level = 2
)

doc <- add_heading(doc, "12. Reusable narrative text", level = 1)
doc <- add_table_section(
  doc,
  "Narrative paragraphs",
  final_report_sections,
  level = 2
)

print(doc, target = word_report_path)

# ------------------------------------------------------------
# 9. Write supporting aggregate outputs
# ------------------------------------------------------------

write_csv(
  core_interpretation_summary,
  file.path(models_dir, "script18l_core_interpretation_summary.csv")
)

write_csv(
  preferred_reporting_models,
  file.path(models_dir, "script18l_preferred_reporting_models.csv")
)

write_csv(
  key_results_narrative_table,
  file.path(models_dir, "script18l_key_results_narrative_table.csv")
)

write_csv(
  limitations_table,
  file.path(models_dir, "script18l_limitations_table.csv")
)

write_csv(
  final_report_sections,
  file.path(models_dir, "script18l_final_report_sections.csv")
)

# ------------------------------------------------------------
# 10. Final status
# ------------------------------------------------------------

final_status <- tibble(
  check = c(
    "script18k_status_loaded",
    "validation_summary_loaded",
    "model_registry_loaded",
    "sample_comparison_loaded",
    "final_model_fit_comparison_loaded",
    "incremental_contribution_summary_loaded",
    "knowledge_selfeff_comparison_loaded",
    "perception_comparison_loaded",
    "vif_summary_loaded",
    "main_findings_loaded",
    "reporting_decisions_loaded",
    "narrative_for_report_loaded",
    "core_interpretation_summary_created",
    "preferred_reporting_models_created",
    "key_results_narrative_table_created",
    "limitations_table_created",
    "final_report_sections_created",
    "word_report_created",
    "no_row_level_output_created",
    "ready_for_final_report_review"
  ),
  status = c(
    nrow(s18k_status) > 0,
    nrow(validation_summary) > 0,
    nrow(model_registry) > 0,
    nrow(sample_comparison) > 0,
    nrow(final_model_fit_comparison) > 0,
    nrow(incremental_contribution_summary) > 0,
    nrow(knowledge_selfeff_comparison) > 0,
    nrow(perception_comparison) > 0,
    nrow(vif_summary) > 0,
    nrow(main_findings) > 0,
    nrow(reporting_decisions) > 0,
    nrow(narrative_for_report) > 0,
    nrow(core_interpretation_summary) > 0,
    nrow(preferred_reporting_models) > 0,
    nrow(key_results_narrative_table) > 0,
    nrow(limitations_table) > 0,
    nrow(final_report_sections) > 0,
    file.exists(word_report_path),
    TRUE,
    TRUE
  )
)

write_csv(
  final_status,
  file.path(models_dir, "script18l_final_status.csv")
)

# ------------------------------------------------------------
# 11. Console output
# ------------------------------------------------------------

cat("\n============================================================\n")
cat("Script 18l completed: Final Modelling Interpretation Report\n")
cat("============================================================\n\n")

cat("Final status:\n")
print(final_status, n = Inf)

cat("\nCore interpretation summary:\n")
print(core_interpretation_summary, n = Inf)

cat("\nPreferred reporting models:\n")
print(preferred_reporting_models, n = Inf)

cat("\nKey results narrative table:\n")
print(key_results_narrative_table, n = Inf)

cat("\nLimitations table:\n")
print(limitations_table, n = Inf)

cat("\nFinal report sections:\n")
print(final_report_sections, n = Inf)

cat("\nWord report created:\n")
cat(word_report_path, "\n")

cat("\nSupporting aggregate outputs created in:\n")
cat(models_dir, "\n")

cat("\nImportant Git note:\n")
cat("Script 18l creates aggregate interpretation outputs only.\n")
cat("No row-level LOCAL_ONLY file is created by this script.\n")
cat("Do not commit yet. Review the Word report first.\n")