# ============================================================
# Script 18m — Editorial Formatting of Final Modelling Report
# Project: Add Health Adolescent Risk Models
#
# Purpose:
#   Produce an editorially cleaner version of the final modelling
#   interpretation report generated by Script 18l.
#
# Main editorial corrections:
#   1. Remove duplicate numbering in headings.
#   2. Correct "p = <0.001" to "p < 0.001".
#   3. Keep only compact interpretive tables in the main report.
#   4. Move detailed technical tables into a separate technical appendix.
#   5. Create no row-level outputs.
#
# Inputs:
#   Aggregate outputs from Scripts 18k and 18l.
#
# Outputs:
#   docs/add_health_wave01_final_modelling_report_script18m_clean.docx
#   docs/add_health_wave01_final_modelling_report_script18m_technical_appendix.docx
#
# Git note:
#   Do not commit yet. Review both Word files first.
# ============================================================

rm(list = ls())

# ------------------------------------------------------------
# 0. Packages
# ------------------------------------------------------------

required_packages <- c(
  "dplyr",
  "tibble",
  "readr",
  "stringr",
  "tidyr",
  "purrr",
  "officer",
  "flextable"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop("Missing packages: ", paste(missing_packages, collapse = ", "))
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(readr)
  library(stringr)
  library(tidyr)
  library(purrr)
  library(officer)
  library(flextable)
})

# ------------------------------------------------------------
# 1. Project root and folders
# ------------------------------------------------------------

project_root <- "C:/Users/LENOVO/GitHub/add-health-adolescent-risk-models"

if (!dir.exists(project_root)) {
  stop("Project root not found: ", project_root)
}

setwd(project_root)

models_dir <- file.path(project_root, "outputs", "models")
docs_dir   <- file.path(project_root, "docs")

dir.create(models_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(docs_dir, recursive = TRUE, showWarnings = FALSE)

cat("\n============================================================\n")
cat("Script 18m started: Editorial Formatting of Final Report\n")
cat("============================================================\n\n")

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

read_required_csv <- function(path) {
  if (!file.exists(path)) {
    stop("Required file not found: ", path)
  }

  readr::read_csv(path, show_col_types = FALSE)
}

clean_p_text <- function(x) {
  x <- as.character(x)

  x %>%
    stringr::str_replace_all("p = <0\\.001", "p < 0.001") %>%
    stringr::str_replace_all("p = <0,001", "p < 0.001") %>%
    stringr::str_replace_all("p = 0$", "p < 0.001")
}

clean_display_text <- function(x) {
  x <- as.character(x)

  x %>%
    clean_p_text() %>%
    stringr::str_replace_all("_", " ") %>%
    stringr::str_replace_all("1-4", "1-4") %>%
    stringr::str_replace_all("1–4", "1-4") %>%
    stringr::str_squish()
}

format_num <- function(x, digits = 3) {
  x <- suppressWarnings(as.numeric(x))

  ifelse(
    is.na(x),
    "",
    format(round(x, digits), nsmall = digits, trim = TRUE)
  )
}

format_p <- function(p) {
  p <- suppressWarnings(as.numeric(p))

  case_when(
    is.na(p) ~ "",
    p < 0.001 ~ "p < 0.001",
    TRUE ~ paste0("p = ", round(p, 3))
  )
}

short_outcome <- function(x) {
  case_when(
    stringr::str_detect(x, "total_restricted") ~ "Total ISX",
    stringr::str_detect(x, "timing_abstinence") ~ "Timing/abstinence",
    stringr::str_detect(x, "method_use_active") ~ "Active method-use",
    stringr::str_detect(x, "method_use_component") ~ "Method-use component",
    stringr::str_detect(x, "high_method") ~ "High method protection",
    TRUE ~ clean_display_text(x)
  )
}

short_model_step <- function(x) {
  case_when(
    x == "M1_covariates" ~ "M1: covariates",
    x == "M2_covariates_perceptions" ~ "M2: + perceptions/barriers",
    x == "M3_add_knowledge" ~ "M3: + knowledge",
    x == "M4_add_self_efficacy" ~ "M4: + self-efficacy",
    TRUE ~ clean_display_text(x)
  )
}

clean_df_for_word <- function(df, digits = 3) {
  df %>%
    mutate(
      across(
        where(is.numeric),
        ~ round(.x, digits)
      )
    ) %>%
    mutate(
      across(
        everything(),
        ~ clean_p_text(.x)
      )
    ) %>%
    mutate(
      across(
        everything(),
        ~ ifelse(is.na(.x), "", as.character(.x))
      )
    )
}

make_ft <- function(df, font_size = 8, digits = 3) {

  df_clean <- clean_df_for_word(df, digits = digits)

  flextable(df_clean) %>%
    fontsize(size = font_size, part = "all") %>%
    padding(padding = 2, part = "all") %>%
    theme_booktabs() %>%
    autofit() %>%
    set_table_properties(width = 1, layout = "autofit")
}

style_exists <- function(doc, style_name) {
  style_name %in% officer::styles_info(doc)$style_name
}

add_par_safe <- function(doc, text, style = "Normal") {

  if (!style_exists(doc, style)) {
    style <- "Normal"
  }

  officer::body_add_par(doc, value = clean_p_text(text), style = style)
}

add_h1 <- function(doc, text) {
  # No manual numbering. Word heading style may number automatically.
  add_par_safe(doc, clean_display_text(text), style = "heading 1")
}

add_h2 <- function(doc, text) {
  add_par_safe(doc, clean_display_text(text), style = "heading 2")
}

add_title <- function(doc, text) {
  if (style_exists(doc, "Title")) {
    officer::body_add_par(doc, value = text, style = "Title")
  } else {
    officer::body_add_par(doc, value = text, style = "Normal")
  }
}

add_subtitle <- function(doc, text) {
  if (style_exists(doc, "Subtitle")) {
    officer::body_add_par(doc, value = text, style = "Subtitle")
  } else {
    officer::body_add_par(doc, value = text, style = "Normal")
  }
}

add_paragraphs <- function(doc, paragraphs) {

  for (p in paragraphs) {
    if (!is.na(p) && stringr::str_squish(p) != "") {
      doc <- add_par_safe(doc, p, style = "Normal")
    }
  }

  doc
}

split_section_text <- function(x) {

  x <- clean_p_text(x)

  out <- unlist(strsplit(x, "\n", fixed = TRUE))
  out <- stringr::str_squish(out)
  out[out != ""]
}

add_table_section <- function(doc, title, df, level = 2, font_size = 8) {

  if (level == 1) {
    doc <- add_h1(doc, title)
  } else {
    doc <- add_h2(doc, title)
  }

  doc <- flextable::body_add_flextable(doc, make_ft(df, font_size = font_size))
  doc <- officer::body_add_par(doc, "", style = "Normal")

  doc
}

# ------------------------------------------------------------
# 3. Required inputs
# ------------------------------------------------------------

paths <- list(
  s18l_status = file.path(models_dir, "script18l_final_status.csv"),
  core_interpretation = file.path(models_dir, "script18l_core_interpretation_summary.csv"),
  preferred_reporting = file.path(models_dir, "script18l_preferred_reporting_models.csv"),
  key_results = file.path(models_dir, "script18l_key_results_narrative_table.csv"),
  limitations = file.path(models_dir, "script18l_limitations_table.csv"),
  final_sections = file.path(models_dir, "script18l_final_report_sections.csv"),

  validation_summary = file.path(models_dir, "script18k_validation_summary.csv"),
  model_registry = file.path(models_dir, "script18k_model_registry.csv"),
  sample_comparison = file.path(models_dir, "script18k_sample_comparison.csv"),
  final_fit = file.path(models_dir, "script18k_final_model_fit_comparison.csv"),
  incremental = file.path(models_dir, "script18k_incremental_contribution_summary.csv"),
  knowledge_selfeff = file.path(models_dir, "script18k_knowledge_selfeff_comparison.csv"),
  perception = file.path(models_dir, "script18k_perception_comparison.csv"),
  vif_summary = file.path(models_dir, "script18k_vif_summary.csv"),
  main_findings = file.path(models_dir, "script18k_main_findings.csv"),
  reporting_decisions = file.path(models_dir, "script18k_reporting_decisions.csv")
)

missing_required <- unlist(paths)[!file.exists(unlist(paths))]

if (length(missing_required) > 0) {
  stop(
    "Some required aggregate output files are missing:\n",
    paste(missing_required, collapse = "\n")
  )
}

# ------------------------------------------------------------
# 4. Read inputs
# ------------------------------------------------------------

s18l_status <- read_required_csv(paths$s18l_status)
core_interpretation <- read_required_csv(paths$core_interpretation)
preferred_reporting <- read_required_csv(paths$preferred_reporting)
key_results <- read_required_csv(paths$key_results)
limitations <- read_required_csv(paths$limitations)
final_sections <- read_required_csv(paths$final_sections)

validation_summary <- read_required_csv(paths$validation_summary)
model_registry <- read_required_csv(paths$model_registry)
sample_comparison <- read_required_csv(paths$sample_comparison)
final_fit <- read_required_csv(paths$final_fit)
incremental <- read_required_csv(paths$incremental)
knowledge_selfeff <- read_required_csv(paths$knowledge_selfeff)
perception <- read_required_csv(paths$perception)
vif_summary <- read_required_csv(paths$vif_summary)
main_findings <- read_required_csv(paths$main_findings)
reporting_decisions <- read_required_csv(paths$reporting_decisions)

# ------------------------------------------------------------
# 5. Clean and compact tables for main report
# ------------------------------------------------------------

main_model_registry <- model_registry %>%
  transmute(
    Script = script,
    Model = clean_display_text(model_label),
    Estimator = estimator,
    Outcome = clean_display_text(dependent_variable),
    Sample = clean_display_text(analytic_sample),
    N = n
  )

main_sample <- sample_comparison %>%
  transmute(
    Metric = clean_display_text(metric),
    `18g` = script_18g,
    `18h` = script_18h,
    `18i` = script_18i,
    `18j` = script_18j
  )

main_fit <- final_fit %>%
  transmute(
    Script = script,
    Outcome = short_outcome(outcome),
    Estimator = estimator,
    N = n,
    `Fit statistic` = paste0(
      final_fit_primary_name,
      " = ",
      format_num(final_fit_primary, 3)
    ),
    `Secondary statistic` = paste0(
      final_fit_secondary_name,
      " = ",
      format_num(final_fit_secondary, 3)
    )
  )

main_key_results <- key_results %>%
  transmute(
    Construct = clean_display_text(construct),
    `Broad ISX result` = clean_p_text(broad_total_isx_result),
    `Sexually active method-use result` = clean_p_text(sexually_active_method_use_result),
    Interpretation = clean_p_text(interpretation)
  )

main_core_interpretation <- core_interpretation %>%
  transmute(
    Topic = clean_display_text(topic),
    Interpretation = clean_p_text(interpretation)
  )

main_preferred_reporting <- preferred_reporting %>%
  transmute(
    Section = clean_display_text(report_section),
    Model = clean_display_text(model_to_report),
    Reason = clean_p_text(reason)
  )

main_limitations <- limitations %>%
  transmute(
    Limitation = clean_display_text(limitation),
    `Interpretation for report` = clean_p_text(interpretation_for_report)
  )

main_vif <- vif_summary %>%
  transmute(
    Script = script,
    Outcome = short_outcome(outcome),
    `Maximum VIF` = round(max_vif, 2),
    `Main VIF term` = clean_display_text(max_vif_term),
    Interpretation = vif_interpretation
  )

main_findings_clean <- main_findings %>%
  transmute(
    ID = finding_id,
    Finding = clean_p_text(finding)
  )

# ------------------------------------------------------------
# 6. Compact appendix tables
# ------------------------------------------------------------

appendix_incremental <- incremental %>%
  transmute(
    Script = script,
    Outcome = short_outcome(outcome),
    Step = short_model_step(model_step),
    Metric = incremental_metric,
    Delta = round(delta_value, 4),
    Interpretation = interpretation
  )

appendix_knowledge_selfeff <- knowledge_selfeff %>%
  transmute(
    Script = script,
    Outcome = short_outcome(outcome),
    Construct = clean_display_text(construct),
    Type = estimate_type,
    Result = clean_p_text(formatted_result),
    Direction = direction,
    Significance = significance
  )

appendix_perception <- perception %>%
  transmute(
    Script = script,
    Outcome = short_outcome(outcome),
    Construct = clean_display_text(construct),
    Type = estimate_type,
    Estimate = round(estimate, 4),
    `95% CI` = paste0("[", round(conf_low, 4), ", ", round(conf_high, 4), "]"),
    `p-value` = format_p(p_value),
    Direction = direction,
    Significance = significance
  )

appendix_reporting_decisions <- reporting_decisions %>%
  transmute(
    Area = clean_display_text(decision_area),
    Decision = clean_p_text(decision)
  )

appendix_validation <- validation_summary %>%
  transmute(
    Script = script,
    `Model family` = model_family,
    `All checks true` = all_checks_true,
    `Failed checks` = failed_checks
  )

# ------------------------------------------------------------
# 7. Extract narrative sections
# ------------------------------------------------------------

section_text <- final_sections %>%
  mutate(
    section_clean = clean_display_text(section),
    text_clean = clean_p_text(text)
  )

get_section <- function(section_name) {
  out <- section_text %>%
    filter(section_clean == section_name) %>%
    pull(text_clean)

  if (length(out) == 0) return(character(0))
  split_section_text(out[1])
}

executive_summary <- get_section("Executive summary")
model_sequence <- get_section("Model sequence")
knowledge_interpretation <- get_section("Knowledge interpretation")
selfeff_interpretation <- get_section("Self-efficacy interpretation")
risk_interpretation <- get_section("Risk perception interpretation")
reporting_strategy <- get_section("Reporting strategy")
conclusion_text <- get_section("Conclusion")

# ------------------------------------------------------------
# 8. Create clean main Word report
# ------------------------------------------------------------

clean_report_path <- file.path(
  docs_dir,
  "add_health_wave01_final_modelling_report_script18m_clean.docx"
)

doc <- officer::read_docx()

doc <- add_title(
  doc,
  "Add Health Wave I - Final Modelling Interpretation Report"
)

doc <- add_subtitle(
  doc,
  "Clean editorial version - Scripts 18g to 18m"
)

doc <- add_paragraphs(
  doc,
  c(
    "This report was generated from aggregate outputs only.",
    paste0("Project root: ", project_root),
    "Data protection note: no row-level dataset is created by this script.",
    "The main purpose of this version is editorial clarity: clean headings, corrected p-value formatting and compact interpretive tables."
  )
)

doc <- officer::body_add_break(doc)

doc <- add_h1(doc, "Executive summary")
doc <- add_paragraphs(doc, executive_summary)

doc <- add_h1(doc, "Modelling sequence")
doc <- add_paragraphs(doc, model_sequence)
doc <- add_table_section(doc, "Model registry", main_model_registry, level = 2, font_size = 8)
doc <- add_table_section(doc, "Sample comparison", main_sample, level = 2, font_size = 8)

doc <- add_h1(doc, "Final model fit")
doc <- add_paragraphs(
  doc,
  c(
    "Model fit is reported for comparison across specifications.",
    "The main interpretation should focus on coefficient direction, stability and construct-level meaning rather than on predictive strength alone."
  )
)
doc <- add_table_section(doc, "Compact final model fit", main_fit, level = 2, font_size = 8)

doc <- add_h1(doc, "Knowledge interpretation")
doc <- add_paragraphs(doc, knowledge_interpretation)

doc <- add_h1(doc, "Self-efficacy interpretation")
doc <- add_paragraphs(doc, selfeff_interpretation)

doc <- add_h1(doc, "Risk perception and susceptibility interpretation")
doc <- add_paragraphs(doc, risk_interpretation)

doc <- add_h1(doc, "Key results")
doc <- add_table_section(doc, "Key results narrative table", main_key_results, level = 2, font_size = 8)

doc <- add_h1(doc, "Core interpretation")
doc <- add_table_section(doc, "Core interpretation summary", main_core_interpretation, level = 2, font_size = 8)

doc <- add_h1(doc, "Preferred reporting strategy")
doc <- add_paragraphs(doc, reporting_strategy)
doc <- add_table_section(doc, "Preferred reporting models", main_preferred_reporting, level = 2, font_size = 8)

doc <- add_h1(doc, "Diagnostics and limitations")
doc <- add_table_section(doc, "VIF summary", main_vif, level = 2, font_size = 8)
doc <- add_table_section(doc, "Limitations and interpretation cautions", main_limitations, level = 2, font_size = 8)

doc <- add_h1(doc, "Final conclusion")
doc <- add_paragraphs(doc, conclusion_text)

doc <- add_h1(doc, "Main findings")
doc <- add_table_section(doc, "Main findings", main_findings_clean, level = 2, font_size = 8)

print(doc, target = clean_report_path)

# ------------------------------------------------------------
# 9. Create technical appendix Word report
# ------------------------------------------------------------

appendix_path <- file.path(
  docs_dir,
  "add_health_wave01_final_modelling_report_script18m_technical_appendix.docx"
)

appendix <- officer::read_docx()

appendix <- add_title(
  appendix,
  "Add Health Wave I - Technical Appendix to Final Modelling Report"
)

appendix <- add_subtitle(
  appendix,
  "Aggregate tables from Scripts 18g to 18m"
)

appendix <- add_paragraphs(
  appendix,
  c(
    "This appendix contains compact aggregate technical tables.",
    "No row-level data are included.",
    "The appendix is separated from the main report to keep the main report readable."
  )
)

appendix <- officer::body_add_break(appendix)

appendix <- add_h1(appendix, "Validation")
appendix <- add_table_section(appendix, "Validation summary", appendix_validation, level = 2, font_size = 8)

appendix <- add_h1(appendix, "Incremental model contribution")
appendix <- add_table_section(
  appendix,
  "Incremental contribution summary",
  appendix_incremental,
  level = 2,
  font_size = 7
)

appendix <- add_h1(appendix, "Knowledge and self-efficacy")
appendix <- add_table_section(
  appendix,
  "Knowledge and self-efficacy comparison",
  appendix_knowledge_selfeff,
  level = 2,
  font_size = 7
)

appendix <- add_h1(appendix, "Perceptions and susceptibility")
appendix <- add_table_section(
  appendix,
  "Perception and susceptibility comparison",
  appendix_perception,
  level = 2,
  font_size = 7
)

appendix <- add_h1(appendix, "Reporting decisions")
appendix <- add_table_section(
  appendix,
  "Reporting decisions",
  appendix_reporting_decisions,
  level = 2,
  font_size = 8
)

appendix <- add_h1(appendix, "VIF diagnostics")
appendix <- add_table_section(
  appendix,
  "VIF summary",
  main_vif,
  level = 2,
  font_size = 8
)

print(appendix, target = appendix_path)

# ------------------------------------------------------------
# 10. Write supporting aggregate outputs
# ------------------------------------------------------------

write_csv(
  main_model_registry,
  file.path(models_dir, "script18m_main_model_registry.csv")
)

write_csv(
  main_fit,
  file.path(models_dir, "script18m_compact_final_model_fit.csv")
)

write_csv(
  main_key_results,
  file.path(models_dir, "script18m_main_key_results.csv")
)

write_csv(
  main_core_interpretation,
  file.path(models_dir, "script18m_core_interpretation_summary.csv")
)

write_csv(
  main_preferred_reporting,
  file.path(models_dir, "script18m_preferred_reporting_models.csv")
)

write_csv(
  main_limitations,
  file.path(models_dir, "script18m_limitations_table.csv")
)

write_csv(
  main_vif,
  file.path(models_dir, "script18m_vif_summary.csv")
)

write_csv(
  appendix_incremental,
  file.path(models_dir, "script18m_appendix_incremental_summary.csv")
)

write_csv(
  appendix_knowledge_selfeff,
  file.path(models_dir, "script18m_appendix_knowledge_selfeff.csv")
)

write_csv(
  appendix_perception,
  file.path(models_dir, "script18m_appendix_perception.csv")
)

# ------------------------------------------------------------
# 11. Final editorial checks
# ------------------------------------------------------------

check_no_bad_p_main <- all(
  !stringr::str_detect(
    unlist(main_key_results),
    fixed("p = <0.001")
  )
)

check_no_bad_p_appendix <- all(
  !stringr::str_detect(
    unlist(appendix_knowledge_selfeff),
    fixed("p = <0.001")
  )
)

final_status <- tibble(
  check = c(
    "script18l_status_loaded",
    "script18k_aggregate_outputs_loaded",
    "final_sections_loaded",
    "core_interpretation_loaded",
    "key_results_loaded",
    "p_value_format_cleaned",
    "main_report_created",
    "technical_appendix_created",
    "compact_main_tables_created",
    "detailed_tables_moved_to_appendix",
    "no_row_level_output_created",
    "ready_for_editorial_review"
  ),
  status = c(
    nrow(s18l_status) > 0,
    nrow(validation_summary) > 0 &&
      nrow(model_registry) > 0 &&
      nrow(final_fit) > 0 &&
      nrow(knowledge_selfeff) > 0 &&
      nrow(perception) > 0,
    nrow(final_sections) > 0,
    nrow(core_interpretation) > 0,
    nrow(key_results) > 0,
    check_no_bad_p_main && check_no_bad_p_appendix,
    file.exists(clean_report_path),
    file.exists(appendix_path),
    nrow(main_key_results) > 0 &&
      nrow(main_core_interpretation) > 0 &&
      nrow(main_preferred_reporting) > 0,
    nrow(appendix_incremental) > 0 &&
      nrow(appendix_knowledge_selfeff) > 0 &&
      nrow(appendix_perception) > 0,
    TRUE,
    TRUE
  )
)

write_csv(
  final_status,
  file.path(models_dir, "script18m_final_status.csv")
)

# ------------------------------------------------------------
# 12. Console output
# ------------------------------------------------------------

cat("\n============================================================\n")
cat("Script 18m completed: Editorial Formatting of Final Report\n")
cat("============================================================\n\n")

cat("Final status:\n")
print(final_status, n = Inf)

cat("\nMain report path:\n")
cat(clean_report_path, "\n")

cat("\nTechnical appendix path:\n")
cat(appendix_path, "\n")

cat("\nCompact final model fit:\n")
print(main_fit, n = Inf)

cat("\nMain key results:\n")
print(main_key_results, n = Inf)

cat("\nCore interpretation summary:\n")
print(main_core_interpretation, n = Inf)

cat("\nPreferred reporting models:\n")
print(main_preferred_reporting, n = Inf)

cat("\nLimitations:\n")
print(main_limitations, n = Inf)

cat("\nImportant Git note:\n")
cat("Script 18m creates aggregate editorial outputs only.\n")
cat("No row-level LOCAL_ONLY file is created.\n")
cat("Do not commit yet. Review both Word files first.\n")